CREATE DATABASE QUANLYDIEM
GO
USE QUANLYDIEM
GO
-----
CREATE TABLE Monhoc 
(msmh CHAR(9) NOT NULL, 
tenmh NVARCHAR(50) NOT NULL)
GO
CREATE TABLE Lop
(malop CHAR(12) NOT NULL, 
msmh CHAR(9) NOT NULL, 
hocky CHAR(5) NOT NULL, 
giangvien NVARCHAR(50) NOT NULL)
GO
CREATE TABLE Sinhvien
(mssv CHAR(7) NOT NULL, 
hoten NVARCHAR(50) NOT NULL, 
nganh CHAR(4) NOT NULL)
GO
CREATE TABLE Hoc
(mssv CHAR(7) NOT NULL, 
malop  CHAR(12) NOT NULL, 
diem DECIMAL(5,2) NOT NULL)

--
ALTER TABLE  Monhoc
ADD CONSTRAINT PK_msmh PRIMARY KEY (msmh)
GO
ALTER TABLE Monhoc
ADD CONSTRAINT UQ_tenmh UNIQUE (tenmh)
GO
ALTER TABLE  Lop
ADD CONSTRAINT PK_malop PRIMARY KEY (malop)
GO
ALTER TABLE  Sinhvien
ADD CONSTRAINT PK_mssv PRIMARY KEY (mssv)
GO
ALTER TABLE Hoc
ADD CONSTRAINT PK_mssv_malop PRIMARY KEY (mssv,malop)
GO
----
ALTER TABLE Lop
ADD CONSTRAINT FK_msmh FOREIGN KEY (msmh) REFERENCES monhoc(msmh) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
ALTER TABLE Hoc
ADD CONSTRAINT FK_mssv FOREIGN KEY (mssv) REFERENCES sinhvien(mssv) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
ALTER TABLE Hoc
ADD CONSTRAINT FK_malop FOREIGN KEY (malop) REFERENCES Lop(malop) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
--
ALTER TABLE hoc
ADD CONSTRAINT CK_diem CHECK (diem >=0 AND diem <=10)
GO
ALTER TABLE monhoc
ADD CONSTRAINT CK_msmh CHECK (msmh like '[A-Z][A-Z][0-9][0-9][0-9]D[VE][0-9][0-9]')
GO
ALTER TABLE sinhvien
ADD CONSTRAINT CK_mssv CHECK (mssv like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
GO
ALTER TABLE Sinhvien
ADD CONSTRAINT DF_nganh DEFAULT 'CNTT' FOR nganh